read.csv("hw1_data")
getwd()
file.open("hw1_data.csv")
read.csv(hw1_data)
read.csv("hw1_data")
?read.csv
read.csv(hw1_data)
library(readr)
hw1_data <- read_csv("hw1_data.csv")
View(hw1_data)
attributes(hw1_data)
colnames(hw1_data)
hw1_data[2]
hw1_data[,2]
?"[]"
df<-read.csv('hw1_data.csv')
df
df[2,]
df[1:2,]
nrow(df)
df[(nrow(df)-1):nrow(df),]
ozoneextract<-df("ozone")
?data.frame
dim(df)
dimnames("ozone")
df[,"ozone"]
df[,"Ozone"]
Ozone_extract<-df[,"Ozone"]
Ozone_extract[47]
sum(Ozone_extract=="NA")
sum(Ozone_extract==NA)
sum(Ozone_extract=='NA')
sum(Ozone_extract==0)
c<-Ozone_extract==0
c
c<-Ozone_extract==NA
c
c<-Ozone_extract=="NA"
c
c<-Ozone_extract=='NA'
c
c<-Ozone_extract=/=NA
c<-Ozone_extract=\=NA
c<-Ozone_extract!==NA
c<-Ozone_extract!=NA
c
is.na(df)
sum(is.na(Ozone_extract))
multiplier<-!is.na(Ozone_extract)
multiplier
sum(multiplier*Ozone_extract)
multiplier*Ozone_extract
validOzone<-Ozone[is.na(Ozone_extract)==FALSE]
validOzone<-Ozone_extract[is.na(Ozone_extract)==FALSE]
validOzone
average(validOzone)
ggplot2
library(ggplot2)
sum(validOzone)
count.field(validOzone)
count.fields(validOzone)
sum(validOzone)/length(validOzone)
temp<-df[,"Temp"]
temp
18<-c(Ozone_extract>31&temp>90)
18<-c( (Ozone_extract>31) & (temp>90) )
18<-(Ozone_extract>31) & (temp>90)
row18<-c((Ozone_extract>31) & (temp>90))
row18
df[c,]
df[row18,]
df18<-df[row18,]
c18<-df18[,"Solar.R"]
c18
process18<-!is.na(c18)
process18
validc18<-c18[is.na(c18)==FALSE]
validc18
sum(validc18)/length(validc18)
c19<-df[,"Month"]
c19
df[,"Month"==6]
df[,"Month"=="6"]
df[,"Month"=='6']
df
df[,month==6]
df[,Month==6]
df[,7>"Month">5]
df[,"Month"=="6"]
df(,"Month"=="6")
df[,"Temp / "Month"]
df[,"Temp & "Month"]
df[,"Temp" & "Month"]
c19<-df[,"Temp"]
c19
c19list<-df[,"Month"]
c19list1<-c19list==6
c19list1
class(c19list1)
cbind(c19,c19list)
totallist<-cbind(c19,c19list)
totallist[,"c19list"==6]
totallist[,"c19list"=="6"]
totallist[,c19list==6]
totallist[,c19list=6]
attributes(totallist)
df
row_19<-c(df[,"Month"]==6)
row_19
sum(row_19)
multi<-c(df[,"Temp"]*row_19)
sum(multi)/30
max(df[,"Ozone"]*df[,"Month"]==5)
max(c(df[,"Ozone"]*df[,"Month"]==5))
?max
max(c(df[,"Ozone"])*c(df[,"Month"]==5))
row_20<-c(df[,"Month"]==5)
row_20
c(df[,"Ozone"])
row_20*c(df[,"Ozone"])
list_20<-row_20*c(df[,"Ozone"])
max(list_20)
list_final<-list_20(!is.na(list_20))
list_final<-list_20[!is.na(list_20)]
list_final
max(list_final)


## quicker way to calculate mean and filter through NA data / function is.na is important here
x<-df["Ozone"]
u<-!is.na(x)
sum(x[u])/length(x[u])

